workflows:
  tui-test:
    name: "TUI Application Test"
    description: "Test workflow for interactive TUI applications"
    initialState: "create-file"
    states:
      create-file:
        description: "Create a test file"
        command: "bash"
        args: ["-c", "echo 'Hello from TUI workflow' > test-tui-file.txt"]
        transitions:
          success: "edit-with-nano"
      edit-with-nano:
        description: "Edit file with nano"
        command: "nano"
        args: ["test-tui-file.txt"]
        stdin: "inherit"
        timeout: 300000
        transitions:
          success: "show-result"
          failure: "cleanup"
      show-result:
        description: "Show edited file content"
        command: "cat"
        args: ["test-tui-file.txt"]
        transitions:
          success: "cleanup"
      cleanup:
        description: "Clean up test file"
        command: "rm"
        args: ["-f", "test-tui-file.txt"]
        transitions:
          success: "complete"
      complete:
        description: "TUI test complete"
        command: "echo"
        args: ["TUI test workflow completed"]
        transitions: {}

  simple-nano:
    name: "Simple Nano Test"
    description: "Simple workflow to test nano editor"
    initialState: "setup"
    states:
      setup:
        description: "Create test file"
        command: "bash"
        args: ["-c", "echo 'Edit this file with nano!' > nano-test.txt"]
        transitions:
          success: "edit"
      edit:
        description: "Open nano editor"
        command: "nano"
        args: ["nano-test.txt"]
        stdin: "inherit"
        timeout: 300000
        transitions:
          success: "opencode"
          failure: "complete"
        confirmation:
          message: "Run nano?"
          timeout: 3000
          defaultAccept: true
      opencode:
        description: "Open opencode"
        command: "opencode"
        stdin: "inherit"
        timeout: 300000
        transitions:
          success: "complete"
          failure: "complete"
        confirmation:
          message: "Run opencode?"
          timeout: 3000
          defaultAccept: true
      complete:
        description: "Done"
        command: "echo"
        args: ["Nano test completed. File nano-test.txt created."]
        transitions: {}

metadata:
  version: "1.0.0"
  created: "2025-10-23"
  modified: "2025-10-23"
