name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [node, bun]
        node-version: [24.x]
        os: [ubuntu-latest, macos-latest]
        exclude:
          # Exclude redundant combinations
          - runtime: node
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          if [ "${{ matrix.runtime }}" == "bun" ]; then
            bun install
          else
            npm ci
          fi

      - name: Build the project
        run: |
          if [ "${{ matrix.runtime }}" == "bun" ]; then
            bun run build
          else
            npm run build
          fi

      - name: Run linting
        run: |
          if [ "${{ matrix.runtime }}" == "bun" ]; then
            bun run lint || echo "Linting issues found (non-fatal)"
          else
            npm run lint || echo "Linting issues found (non-fatal)"
          fi

      - name: Test Runtime Compatibility
        run: |
          if [ "${{ matrix.runtime }}" == "bun" ]; then
            bun test
          else
            npm test
          fi

      - name: Upload coverage to Codecov
        if: matrix.runtime == 'bun'
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security audit
        run: npm audit --audit-level moderate
